[package]
name = "pomodoro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
notify-rust = "4.0"
async-std = "1.10"
tokio = { version = "1", features = ["full"]}
